# @package _global_
defaults:
  - default

model:
  _target_: mvtracker.models.core.monocular_baselines.MonocularToMultiViewAdapter
  model:
    _target_: mvtracker.models.core.monocular_baselines.CoTrackerOnlineWrapper
    model_name: cotracker3_online
    grid_size: 10
