# @package _global_
defaults:
  - default

model:
  _target_: mvtracker.models.core.mvtracker.mvtracker.MVTracker
  sliding_window_len: 12
  stride: 4
  normalize_scene_in_fwd_pass: false
  fmaps_dim: 128
  add_space_attn: true
  num_heads: 6
  hidden_size: 256
  space_depth: 6
  time_depth: 6
  num_virtual_tracks: 64
  use_flash_attention: true
  corr_n_groups: 1
  corr_n_levels: 4
  corr_neighbors: 16
  corr_add_neighbor_offset: true
  corr_add_neighbor_xyz: false
  corr_filter_invalid_depth: false   # slower, but would make sure points with invalid depth are not considered in corr

evaluation:
  interp_shape: [ 384, 512 ]

  predictor_settings:
    kubric:
      visibility_threshold: 0.5
      grid_size: 4
      local_grid_size: 18
    dex_ycb:
      visibility_threshold: 0.01
      grid_size: 4
      local_grid_size: 18
    panoptic:
      visibility_threshold: 0.01
      grid_size: 6
      local_grid_size: 18
    tapvid2d-davis:
      visibility_threshold: 0.01
      grid_size: 6
      n_grids_per_view: 6
      local_grid_size: 0
      local_extent: 50
      sift_size: 0
      num_uniformly_sampled_pts: 0
    generic:
      visibility_threshold: 0.01
      grid_size: 4
      local_grid_size: 18

trainer:
  precision: bf16-mixed
