# @package _global_
defaults:
  - default

model:
  _target_: mvtracker.models.core.spatracker.spatracker_monocular.SpaTrackerMultiViewAdapter

  sliding_window_len: 12
  stride: 4
  add_space_attn: true
  num_heads: 8
  hidden_size: 384
  space_depth: 6
  time_depth: 6
  triplane_zres: 128

evaluation:
  interp_shape: [ 512, 512 ]    # This checkpoint was trained on 512x512 Kubric sequences
  predictor_settings:
    kubric:
      visibility_threshold: 0.5
      grid_size: 4
      local_grid_size: 18
    dex_ycb:
      visibility_threshold: 0.5
      grid_size: 0
      local_grid_size: 18
    panoptic:
      visibility_threshold: 0.5
      grid_size: 4
      local_grid_size: 18

#restore_ckpt_path: checkpoints/spatracker_monocular_trained-on-kubric-depth_069800.pth
#restore_ckpt_path: checkpoints/spatracker_monocular_trained-on-duster-depth_090800.pth
